#include "driverlib.h"
#include "device.h"
#include "board.h"
#include "c2000ware_libraries.h"

#include "tjx_init.h"

#include "bsp_motor_hallencoder.h"


// extern volatile uint32_t Encoder_Count;         // 编码器计数，用于用户使用。
// extern volatile uint32_t Encoder_Last_Count;    // 存储上一次中断时的编码器位置值
// extern volatile int32_t  Motor_dir;             // 电机旋转方向（正转/反转）

void main(void)
{
    /* The initialization code automatically generated by CCS [Start] */
    Device_init();
    Device_initGPIO();
    Interrupt_initModule();
    Interrupt_initVectorTable();
    Board_init();
    C2000Ware_libraries_init();
    EINT;
    ERTM;
    /* The initialization code automatically generated by CCS [End] */

    lc_printf("\r\n= = = = = = = = = = = = = = = = = = = = = = = = =\r\n");
    lc_printf("\r\n=== Welcome to use the LC-TJX-TMS320F28P550 ====\r\n");
    lc_printf("\r\n============== www.lckfb.com ===================\r\n");
    lc_printf("\r\n============== wiki.lckfb.com ==================\r\n");
    lc_printf("\r\n= = = = = = = = = = = = = = = = = = = = = = = = =\r\n");

    Encoder_Init();
    
    while(1)
    {
        // 电流太小，驱不动，尽量使用驱动板
        // Motor_Set_PWM(1, 5000);

        DINT;
        uint32_t value = Get_Encoder_Value();
        int32_t dir = Get_Encoder_Dir();
        EINT;
        
        lc_printf("\r\n");
        lc_printf("Encoder_Count = [%lu]\r\n", value);
        lc_printf("Motor_dir     = [%d]\r\n", dir);

        // RGB的B灯亮起，G灯熄灭
        GPIO_writePin(RGB_B, 0);
        GPIO_writePin(RGB_G, 1);
        delay_ms(50);

        // RGB的G灯亮起，B灯熄灭
        GPIO_writePin(RGB_B, 1);
        GPIO_writePin(RGB_G, 0);
        delay_ms(50);

        // RGB的B和G都熄灭
        GPIO_writePin(RGB_B, 1);
        GPIO_writePin(RGB_G, 1);
        delay_ms(50);
    }
}

__interrupt void INT_Debug_Serial_RX_ISR(void)
{
    //清除接收中断标志位
    SCI_clearInterruptStatus(SCIA_BASE, SCI_INT_RXFF);
    //清除中断标志位
    Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP9);
}

