#include "driverlib.h"
#include "device.h"
#include "board.h"
#include "c2000ware_libraries.h"

#include "tjx_init.h"

#include "bsp_motor_hallencoder.h"

#include "app/cli.h"
#include "app/eqep_abi.h"
#include "app/speed_est.h"
#include "app/snap_bin.h"

extern unsigned int g_snap_n;


// extern volatile uint32_t Encoder_Count;         // 编码器计数，用于用户使用。
// extern volatile uint32_t Encoder_Last_Count;    // 存储上一次中断时的编码器位置值
// extern volatile int32_t  Motor_dir;             // 电机旋转方向（正转/反转）

volatile uint32_t g_tick_1khz = 0;   // 1kHz CPU Timer 节拍计数

// 电机闭环测试序列（循环）：停5s -> 斜坡启动+闭环锁定1500RPM(20s) -> 停5s -> 斜坡+闭环2000RPM(20s) -> 停5s -> 循环
#define SEQ_TARGET_CNT 2u
static const uint16_t g_seq_targets[SEQ_TARGET_CNT] = { 1500u, 2000u };  // 目标 RPM
#define SEQ_CTRL_MS    500u          // 闭环控制周期 500ms
#define SEQ_RAMP_MS    40u           // 斜坡步进周期 40ms
#define SEQ_RAMP_STEP  40u           // 斜坡每步 +40 speed（0→1000 约 1s）
#define SEQ_ADJ_MAX    100u          // 闭环单次最大调整
#define SEQ_SPD_MIN    800u
#define SEQ_SPD_MAX    9000u
static uint8_t  g_seq_state = 0;
static uint32_t g_seq_start = 0;
static uint32_t g_ctrl_tick = 0;
static uint32_t g_ramp_tick = 0;
static uint16_t g_speed     = 0;
static int32_t  g_pi_int    = 0;
static uint16_t pi_target_rpm = 0;
static uint8_t  g_seq_done  = 0;   // 全部科目跑完 → 停止电机，不再循环

// PID 闭环：调整脉宽档位使实际转速逼近目标 RPM (feedback from UTO speed_est)
static void Motor_CloseLoop(uint32_t tick)
{
    if (tick - g_ramp_tick >= SEQ_RAMP_MS) {
        g_ramp_tick = tick;
        if (g_speed < 1000u) {
            g_speed = (uint16_t)(g_speed + SEQ_RAMP_STEP);
            return;
        }
    }
    if (tick - g_ctrl_tick >= SEQ_CTRL_MS) {
        g_ctrl_tick = tick;
        uint32_t rpm_now = spd_rpm();
        if (rpm_now > 0) {
            int32_t err = (int32_t)pi_target_rpm - (int32_t)rpm_now;
            g_pi_int += err;
            if (g_pi_int > 2500)  g_pi_int = 2500;
            if (g_pi_int < -2500) g_pi_int = -2500;
            int32_t adj = err / 2 + g_pi_int / 8;
            if (adj > SEQ_ADJ_MAX)  adj = SEQ_ADJ_MAX;
            if (adj < -(int32_t)SEQ_ADJ_MAX) adj = -(int32_t)SEQ_ADJ_MAX;
            int32_t spd = (int32_t)g_speed + adj;
            if (spd < SEQ_SPD_MIN) spd = SEQ_SPD_MIN;
            if (spd > SEQ_SPD_MAX) spd = SEQ_SPD_MAX;
            g_speed = (uint16_t)spd;
        }
    }
}

void main(void)
{
    /* The initialization code automatically generated by CCS [Start] */
    Device_init();
    Device_initGPIO();
    Interrupt_initModule();
    Interrupt_initVectorTable();
    Board_init();
    C2000Ware_libraries_init();
    EINT;
    ERTM;
    /* The initialization code automatically generated by CCS [End] */

    lc_printf("\r\n= = = = = = = = = = = = = = = = = = = = = = = = =\r\n");
    lc_printf("\r\n=== Welcome to use the LC-TJX-TMS320F28P550 ====\r\n");
    lc_printf("\r\n============== www.lckfb.com ===================\r\n");
    lc_printf("\r\n============== wiki.lckfb.com ==================\r\n");
    lc_printf("\r\n= = = = = = = = = = = = = = = = = = = = = = = = =\r\n");

    Encoder_Init();
    Motor_Init();
    cli_init();
    abi_init();
    spd_init();
    snap_alloc();
    g_seq_start = g_tick_1khz;

    while(1)
    {
        // Motor always off (closed-loop test disabled for clean snap test)
        Motor_Set_PWM(1, 0);

        /* Minimal 1Hz status line */
        static uint32_t dbg_tick = 0;
        if (g_tick_1khz - dbg_tick >= 1000) {
            dbg_tick = g_tick_1khz;
            uint32_t rpm = spd_rpm();
            lc_printf("RPM=[%lu] SNAP=[%u/%u]\r\n",
                      (unsigned long)rpm, (unsigned)g_snap_n, (unsigned)SNAP_CAP);
        }

        cli_task();
        snap_poll(spd_rpm());

        /* LED indicators based on snap state */
        {
            int armed = snap_armed();
            if (snap_done()) {
                GPIO_writePin(RGB_B, 0);  /* B on */
                GPIO_writePin(RGB_G, 0);  /* G on → purple */
            } else if (g_alive) {
                GPIO_writePin(RGB_B, 1);
                GPIO_writePin(RGB_G, 0);  /* G on → green */
            } else if (g_recording) {
                static int blip = 0;
                blip++;
                GPIO_writePin(RGB_G, blip & 4 ? 0 : 1); /* G flash → recording */
                GPIO_writePin(RGB_B, 1);
            } else if (armed) {
                GPIO_writePin(RGB_B, 0);  /* B on → blue */
                GPIO_writePin(RGB_G, 1);
            } else {
                GPIO_writePin(RGB_B, 1);
                GPIO_writePin(RGB_G, 1);  /* both off */
            }
        }
    }
}

__interrupt void INT_Debug_Serial_RX_ISR(void)
{
    // 读取接收到的字符，推入 CLI 环形缓冲区（读 SCIRXBUF 会自动清除 RXRDY 标志）
    uint16_t rx = SCI_readCharNonBlocking(SCIA_BASE);
    cli_push_rx((char)(rx & 0xFFU));
    // 清除 FIFO 中断标志（FIFO 禁用时为无操作）
    SCI_clearInterruptStatus(SCIA_BASE, SCI_INT_RXFF);
    // 清除 PIE 中断应答
    Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP9);
}

// 1kHz CPU Timer 节拍中断
__interrupt void INT_myCPUTIMER0_ISR(void)
{
    g_tick_1khz++;
    abi_clock_tick();
    spd_tick_1khz();
    Encoder_Periodic_Update();
    Interrupt_clearACKGroup(INT_myCPUTIMER0_INTERRUPT_ACK_GROUP);
}

